#!/bin/sh

FILE="${FILE:-$PLUGIN_FILE}"
PASSWORD="${PASSWORD:-$PLUGIN_PASSWORD}"
SERVER="${SERVER:-$PLUGIN_SERVER}"
USER="${USER:-$PLUGIN_USER}"
VERBOSE="${VERBOSE:-$PLUGIN_VERBOSE}"
WEBDAV_PATH="${WEBDAV_PATH:-$PLUGIN_WEBDAV_PATH}"
WEBDAV_PREFIX="${WEBDAV_PREFIX:-$PLUGIN_WEBDAV_PREFIX}"
WEBDAV_USER="${WEBDAV_USER:-$PLUGIN_WEBDAV_USER}"

if [ -z "$USER" ]; then
    echo "No username provided... please user environment variable USER"
    exit 1
elif [ -z "$SERVER" ]; then
    echo "No server url provided... please user environment variable SERVER"
    exit 1
elif [ ! -r "$FILE" ]; then
    echo "Could not open file $FILE... either it does not exist, or read permission is not granted"
    exit 1
fi

WEBDAV_PREFIX="${WEBDAV_PREFIX:-remote.php/dav/files}"
WEBDAV_USER="${WEBDAV_USER:-$USER}"
WEBDAV_URL="$SERVER"/"$WEBDAV_PREFIX"/"$WEBDAV_USER"/"$WEBDAV_PATH"

if [ "$VERBOSE" = "yes" ]; then;
    VERBOSE_FLAG="--verbose"
    echo "
--------------------------------------------------
FILE:          $FILE
SERVER:        $SERVER
USER:          $USER
VERBOSE:       $VERBOSE
WEBDAV_PATH:   $WEBDAV_PATH
WEBDAV_PREFIX: $WEBDAV_PREFIX
WEBDAV_URL:    $WEBDAV_URL
WEBDAV_USER:   $WEBDAV_USER
--------------------------------------------------
"
else
    VERBOSE=no
    VERBOSE_FLAG=
    echo "
--------------------------------------------------
FILE:          $FILE
VERBOSE:       $VERBOSE
WEBDAV_PATH:   $WEBDAV_PATH
WEBDAV_PREFIX: $WEBDAV_PREFIX
--------------------------------------------------
"
fi

curl --upload-file "$FILE" --user "$USER:$PASSWORD" $VERBOSE_FLAG "$WEBDAV_URL"
