#!/bin/sh

if [ -z "$USER" ]; then
    echo "No username provided... please user environment variable USER rto"
    exit 1
elif [ -z "$SERVER" ]; then
    echo "No server url provided... please user environment variable SERVER"
    exit 1
elif [ ! -r "$FILE" ]; then
    echo "Could not open file $FILE... either it does not exist, or read permission is not granted"
    exit 1
fi

WEBDAV_PREFIX="${WEBDAV_PREFIX:-remote.php/dav/files}"
WEBDAV_USER="${WEBDAV_USER:-$USER}"
DESTINATION_URL="$SERVER"/"$WEBDAV_PREFIX"/"$WEBDAV_USER"/"$WEBDAV_PATH"

curl --upload-file "$FILE" --user "$USER:$PASSWORD" "$DESTINATION_URL"
